---
followed_nodes:
  - njust

operators:
  college_pass:
    title: 通过
    from_status: 0
    to_status: 1
  college_fail:
    title: 拒绝
    from_status: 0
    to_status: 2
  univers_pass:
    title: 通过
    from_status: 1
    to_status: 3
  univers_fail:
    title: 拒绝
    from_status: 1
    to_status: 4

need_access_control: true

# group:
#   GROUPID:
#     organizations:
#       - ORG-CODE
#     operators:
#       - UNIQ-KEY


...
